cockpit-machines require usbredir in qemu to solve this problem
<pre>
Currently creating a VM from cockpit failed:
error: Failed to define domain from /tmp/tmpfedkb562 error: unsupported configuration: USB redirection is not supported by this version of QEMU
</pre>

This fix issue #9

Signed-off-by: Fco Javier Felix <ffelix@inode64.com>